name: Server CI

on:
  pull_request:
    branches: ["main"]

jobs:
  test-server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "server/yarn.lock"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run NestJS Tests
        run: yarn test
